### PR TITLE
Prevent report generation with scenario but no base model

### LINKED ISSUE #72: Prevent report generation with scenario but no base model
On selecting a scenario in the "Download a report" tab without its associated base model, we would like to prevent selection of the PDF button and display next to it to the message:

> This option is not available because you have selected one or more scenarios without their associated base models

---

The PDF endpoint requires that any scenarios are accompanied by their associated base model.

However, it is currently possible to POST a scenario by itself, _without_ its associated base model, to the PDF end point. This will cause the endpoint to return an error:

image

image

We would like to prevent this happening.

@DavidUnderdown and I are in agreement that a reasonable approachable would be to prevent the selection of the PDF button when a scenario is selected without its base model. Something similar is already implemented when a user tries to generate a CSV for an advanced model:

image

### PR DESCRIPTION
**Pull request by timbrock**
Closes #72

### CODE REVIEW

**Comment by jwalton3141** [comment]
Looks great to me ! Thanks Tim. Assigning to @DavidUnderdown to approve if happy. David, you can test these changes via the development site

image

image

**Comment by DavidUnderdown** [comment]
Just noticing a typo there - it may just be the model name thinking about it, bassline (as in a song), rather than baseline

**Comment by jwalton3141** [comment]
Sorry, yes, that is me spreading confusion (and making the fatal mistake of thinking I'm funny in my own head). it's just what I named the model!

**Review by DavidUnderdown — APPROVED** [review]
Behaves as expected, thanks. Tested the various combinations for selecting base model with or without scenario, and with or without an advanced model. Also checked CSV where applicable and JSON download just to make sure that nothing else appeared broken

**Pull request merged**
