### PR TITLE
Add accessibility statement

### PR DESCRIPTION
**Pull request by timbrock**
* Still contains placeholders.
* Had to remove "content: url(/_images/divider.svg);" from main.css because divider.svg appears not to exist.

@DavidUnderdown do you want to fill in the placeholders and add anything you'd like to say about issues being resolved?

### CODE REVIEW

**Comment by DavidUnderdown** [comment]
Hi Tim, I think I've completed all the placeholders appropriately

**Comment by timbrock** [comment]
I think you've just missed one [here](https://github.com/nationalarchives/DiAGRAM/blob/8ba8461d77a6fb77a70e26a8a0bc6a5fe174965c/app/frontend/accessibility/statement.html#L51) @DavidUnderdown.

**Comment by DavidUnderdown** [comment]
Oh yes, now done. Thanks

**Review by DavidUnderdown — APPROVED** [review]
Having filled in the blanks everything else seems OK

**Pull request merged**
